import "./globals.css";
import Toaster from "./Toaster";

export const metadata = {
  title: "Wordle Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen bg-slate-100 dark:bg-black dark:text-white">
        <Toaster toastOptions={{ position: "top-center" }} />
        {children}
      </body>
    </html>
  );
}
